(define test-1
  '((b e a r -)
    (b e l l -)
    (b i d -)
    (b u l l -)
    (b u y -)
    (s e l l -)
    (s t o c k -)
    (s t o p -)))

(define result-1 ;; = (merge test-1)
  '((branch b ((branch e ((branch a ((branch r ((branch - ())))))
			  (branch l ((branch l ((branch - ())))))))
	       (branch i ((branch d ((branch - ())))))
	       (branch u ((branch l ((branch l ((branch - ())))))
			  (branch y ((branch - ())))))))
    (branch s ((branch e ((branch l ((branch l ((branch - ())))))))
	       (branch t ((branch o ((branch c ((branch k ((branch - ())))))
				     (branch p ((branch - ())))))))))))
